spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/movie_ticket_booking_system
    username: shiv
    password: password
    driver-class-name: org.postgresql.Driver

  server:
    port: 8081

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    differ-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: postgres

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  file:
    name: logs/myapp.log
  level:
    root: INFO

management:
  endpoint:
    shutdown:
      enabled: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoints:
    web:
      exposure:
        include: "*"
    loggers:
      enabled: true
