spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_ticket_booking_system
    user: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8081

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  logging:
    file:
      name: logs/movie-ticket-booking-system-logs.log
    level:
      root: INFO

  management:
    endpoint:
      shutdown:
        enabled: true
      web:
        exposure:
          include: "*"
          exclude: "env, beans"
    endpoints:
      loggers:
        enabled: true
